/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.silviohermida.app;

import com.silviohermida.jdbc.Database;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class Actualizar extends javax.swing.JFrame {

    /**
     * Creates new form Actualizar
     */
    public Actualizar() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.etiquetaIDResultado.setText(""+Database.getUsuarioActual().getIdUsuario());
        this.etiquetaResultadoFecha.setText(Database.getUsuarioActual().getFechaNacimiento());
        this.setTitle("Conectado como: "+Database.getUsuarioActual().getNombre());
        }
    
    
    public void actualizar(){
        String nombre = this.campoActualizarNombre.getText();
        String apellidos = this.campoActualizarApellidos.getText();
        String idUsuario = this.etiquetaIDResultado.getText();
        try{
            Database.ActualizarRegistro(nombre, apellidos, idUsuario);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Problemas al actualizar el usuario"+e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaID = new javax.swing.JLabel();
        etiquetaIDResultado = new javax.swing.JLabel();
        etiquetaNombre = new javax.swing.JLabel();
        campoActualizarNombre = new javax.swing.JTextField();
        etiquetaApellidos = new javax.swing.JLabel();
        campoActualizarApellidos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        etiquetaResultadoFecha = new javax.swing.JLabel();
        etiquetaVacia = new javax.swing.JLabel();
        botonActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(5, 2));

        etiquetaID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaID.setText("ID");
        getContentPane().add(etiquetaID);
        getContentPane().add(etiquetaIDResultado);

        etiquetaNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaNombre.setText("Nombre");
        getContentPane().add(etiquetaNombre);
        getContentPane().add(campoActualizarNombre);

        etiquetaApellidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaApellidos.setText("Apellidos");
        getContentPane().add(etiquetaApellidos);
        getContentPane().add(campoActualizarApellidos);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Fecha de Nacimiento");
        getContentPane().add(jLabel5);
        getContentPane().add(etiquetaResultadoFecha);
        getContentPane().add(etiquetaVacia);

        botonActualizar.setText("Actualizar");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventoActualizar(evt);
            }
        });
        getContentPane().add(botonActualizar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eventoActualizar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventoActualizar
        actualizar();
    }//GEN-LAST:event_eventoActualizar

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JTextField campoActualizarApellidos;
    private javax.swing.JTextField campoActualizarNombre;
    private javax.swing.JLabel etiquetaApellidos;
    private javax.swing.JLabel etiquetaID;
    private javax.swing.JLabel etiquetaIDResultado;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaResultadoFecha;
    private javax.swing.JLabel etiquetaVacia;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
