/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.silviohermida.app;

import com.silviohermida.jdbc.Database;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class Borrar extends javax.swing.JFrame {

    /**
     * Creates new form Borrar
     */
    public Borrar() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Conectado como: "+Database.getUsuarioActual().getNombre());
    }
    
    public void borrar(){
        String idUsuario = this.campoID.getText();
        try{
            Database.borrarUsuario(idUsuario);
            JOptionPane.showMessageDialog(null,"Usuario Borrado Exitosamente","Borrar Usuario",JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showConfirmDialog(null, "Error al Borrar Usuario "+e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaUsuario = new javax.swing.JLabel();
        campoID = new javax.swing.JTextField();
        etiquetaVacia = new javax.swing.JLabel();
        botonBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 2));

        etiquetaUsuario.setText("Id del Usuario");
        getContentPane().add(etiquetaUsuario);
        getContentPane().add(campoID);
        getContentPane().add(etiquetaVacia);

        botonBorrar.setText("Borrar");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventoBotonBorrar(evt);
            }
        });
        getContentPane().add(botonBorrar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eventoBotonBorrar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventoBotonBorrar
        borrar();
    }//GEN-LAST:event_eventoBotonBorrar

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrar;
    private javax.swing.JTextField campoID;
    private javax.swing.JLabel etiquetaUsuario;
    private javax.swing.JLabel etiquetaVacia;
    // End of variables declaration//GEN-END:variables
}
