 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.silviohermida.app;

import com.silviohermida.jdbc.Database;
import com.silviohermida.pojos.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class Buscar extends javax.swing.JFrame {

    /**
     * Creates new form Buscar
     */
    public Buscar() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Conectado como "+Database.getUsuarioActual().getNombre());
        
    }
    
    public void buscar(){
        String ID = this.campoBuscar.getText();
        Usuario usuario;
        
        try{
            usuario = Database.buscarUsuario(ID);
            if(usuario!=null){
                this.resultadoID.setText(""+usuario.getIdUsuario());
                this.resultadoNombre.setText(usuario.getNombre());
                this.resultadoApellidos.setText(usuario.getApellidos());
                this.resultadoNacimeinto.setText(usuario.getFechaNacimiento());
                this.resultadoRegistro.setText(usuario.getRegistro());
                
            }
        }catch(Exception e){
            JOptionPane.showConfirmDialog(null, "ID incorrecto "+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNorte = new javax.swing.JPanel();
        etiquetaBuscar = new javax.swing.JLabel();
        campoBuscar = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        panelCentro = new javax.swing.JPanel();
        etiquetaID = new javax.swing.JLabel();
        resultadoID = new javax.swing.JLabel();
        etiquetaNombre = new javax.swing.JLabel();
        resultadoNombre = new javax.swing.JLabel();
        etiquetaApellidos = new javax.swing.JLabel();
        resultadoApellidos = new javax.swing.JLabel();
        etiquetaNacimiento = new javax.swing.JLabel();
        resultadoNacimeinto = new javax.swing.JLabel();
        etiquetaRegistro = new javax.swing.JLabel();
        resultadoRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        etiquetaBuscar.setText("ID");
        panelNorte.add(etiquetaBuscar);

        campoBuscar.setColumns(10);
        panelNorte.add(campoBuscar);

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventoBotonBuscar(evt);
            }
        });
        panelNorte.add(botonBuscar);

        getContentPane().add(panelNorte, java.awt.BorderLayout.PAGE_START);

        panelCentro.setLayout(new java.awt.GridLayout(5, 2));

        etiquetaID.setText("ID");
        panelCentro.add(etiquetaID);

        resultadoID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panelCentro.add(resultadoID);

        etiquetaNombre.setText("Nombre");
        panelCentro.add(etiquetaNombre);

        resultadoNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panelCentro.add(resultadoNombre);

        etiquetaApellidos.setText("Apellidos");
        panelCentro.add(etiquetaApellidos);

        resultadoApellidos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panelCentro.add(resultadoApellidos);

        etiquetaNacimiento.setText("Fecha de Nacimiento");
        panelCentro.add(etiquetaNacimiento);

        resultadoNacimeinto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panelCentro.add(resultadoNacimeinto);

        etiquetaRegistro.setText("Fecha de Registro");
        panelCentro.add(etiquetaRegistro);

        resultadoRegistro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panelCentro.add(resultadoRegistro);

        getContentPane().add(panelCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eventoBotonBuscar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventoBotonBuscar
       buscar();
    }//GEN-LAST:event_eventoBotonBuscar

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JTextField campoBuscar;
    private javax.swing.JLabel etiquetaApellidos;
    private javax.swing.JLabel etiquetaBuscar;
    private javax.swing.JLabel etiquetaID;
    private javax.swing.JLabel etiquetaNacimiento;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaRegistro;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelNorte;
    private javax.swing.JLabel resultadoApellidos;
    private javax.swing.JLabel resultadoID;
    private javax.swing.JLabel resultadoNacimeinto;
    private javax.swing.JLabel resultadoNombre;
    private javax.swing.JLabel resultadoRegistro;
    // End of variables declaration//GEN-END:variables
}
