/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.silviohermida.app;

import com.silviohermida.jdbc.Database;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class CambiarContraseña extends javax.swing.JFrame {

    /**
     * Creates new form CambiarContraseña
     */
    public CambiarContraseña() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Conectado como: " + Database.getUsuarioActual().getNombre());

    }

    public void cambiar() {
        char[] pass = this.campoActual.getPassword();
        String password = "";
        char[] newPass = this.campoNueva.getPassword();
        String newPassword = "";
        char[] secondPass = this.campoRepetir.getPassword();
        String secondPassword = "";

        for (int i = 0; i < pass.length; i++) {
            password = password + pass[i];
        }
        for (int i = 0; i < newPass.length; i++) {
            newPassword = newPassword + newPass[i];
        }
        for (int i = 0; i < secondPass.length; i++) {
            secondPassword = secondPassword + secondPass[i];
        }

        if (newPassword.equals(secondPassword)) {
            try {
                int respuesta = JOptionPane.showConfirmDialog(null, "¿Desea Confirmar Cambio? ", "Confirmación", JOptionPane.YES_NO_OPTION);
                if (respuesta == 0) {
                    Database.cambiarContraseña(password, newPassword);
                    this.dispose();
                } else {
                    this.campoActual.setText("");
                    this.campoNueva.setText("");
                    this.campoRepetir.setText("");

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Contraseña Incorrecta " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaActual = new javax.swing.JLabel();
        campoActual = new javax.swing.JPasswordField();
        etiquetaNueva = new javax.swing.JLabel();
        campoNueva = new javax.swing.JPasswordField();
        etiquetaRepetir = new javax.swing.JLabel();
        campoRepetir = new javax.swing.JPasswordField();
        etiquetaVcia = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(4, 2));

        etiquetaActual.setText("Contraseña Actual");
        getContentPane().add(etiquetaActual);
        getContentPane().add(campoActual);

        etiquetaNueva.setText("Nueva Contraseña");
        getContentPane().add(etiquetaNueva);
        getContentPane().add(campoNueva);

        etiquetaRepetir.setText("Repita Contraseña");
        getContentPane().add(etiquetaRepetir);
        getContentPane().add(campoRepetir);
        getContentPane().add(etiquetaVcia);

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventoBotonAceptar(evt);
            }
        });
        getContentPane().add(botonAceptar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eventoBotonAceptar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventoBotonAceptar
        cambiar();
    }//GEN-LAST:event_eventoBotonAceptar

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JPasswordField campoActual;
    private javax.swing.JPasswordField campoNueva;
    private javax.swing.JPasswordField campoRepetir;
    private javax.swing.JLabel etiquetaActual;
    private javax.swing.JLabel etiquetaNueva;
    private javax.swing.JLabel etiquetaRepetir;
    private javax.swing.JLabel etiquetaVcia;
    // End of variables declaration//GEN-END:variables
}
