/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.silviohermida.app;



/**
 *
 * @author hp
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
       
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panelCentro = new javax.swing.JPanel();
        etiquetaNombre = new javax.swing.JLabel();
        etiquetaVacia4 = new javax.swing.JLabel();
        campoNombreUsuario = new javax.swing.JTextField();
        etiquetaPassword = new javax.swing.JLabel();
        etiquetaVacia3 = new javax.swing.JLabel();
        campoPassword = new javax.swing.JPasswordField();
        etiquetaVacia1 = new javax.swing.JLabel();
        etiquetaVacia2 = new javax.swing.JLabel();
        botonIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelCentro.setLayout(new java.awt.GridLayout(3, 3));

        etiquetaNombre.setText("Nombre de Usuario");
        panelCentro.add(etiquetaNombre);
        panelCentro.add(etiquetaVacia4);
        panelCentro.add(campoNombreUsuario);

        etiquetaPassword.setText("Contraseña");
        panelCentro.add(etiquetaPassword);
        panelCentro.add(etiquetaVacia3);
        panelCentro.add(campoPassword);
        panelCentro.add(etiquetaVacia1);
        panelCentro.add(etiquetaVacia2);

        botonIngresar.setText("Ingresar");
        panelCentro.add(botonIngresar);

        getContentPane().add(panelCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton botonIngresar;
    private javax.swing.JTextField campoNombreUsuario;
    private javax.swing.JPasswordField campoPassword;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaPassword;
    private javax.swing.JLabel etiquetaVacia1;
    private javax.swing.JLabel etiquetaVacia2;
    private javax.swing.JLabel etiquetaVacia3;
    private javax.swing.JLabel etiquetaVacia4;
    private javax.swing.JPanel panelCentro;
    // End of variables declaration                   
}
