/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.silviohermida.app;

/**
 *
 * @author hp
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNombre = new javax.swing.JPanel();
        etiquetaLiverpool = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuUsuario = new javax.swing.JMenu();
        opcionBuscar = new javax.swing.JMenuItem();
        opcionActualizar = new javax.swing.JMenuItem();
        opcionBorrar = new javax.swing.JMenuItem();
        opcionRegistrar = new javax.swing.JMenuItem();
        opcionContraseña = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 255));
        setLocation(new java.awt.Point(100, 100));
        setMinimumSize(new java.awt.Dimension(500, 500));

        panelNombre.setForeground(new java.awt.Color(0, 0, 255));
        panelNombre.setLayout(new java.awt.GridLayout(1, 0));

        etiquetaLiverpool.setForeground(new java.awt.Color(204, 0, 204));
        etiquetaLiverpool.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaLiverpool.setText("LIVERPOOL");
        etiquetaLiverpool.setMaximumSize(new java.awt.Dimension(300, 300));
        etiquetaLiverpool.setMinimumSize(new java.awt.Dimension(300, 300));
        panelNombre.add(etiquetaLiverpool);

        getContentPane().add(panelNombre, java.awt.BorderLayout.CENTER);

        barraMenu.setForeground(java.awt.Color.cyan);

        menuUsuario.setText("Usuario");

        opcionBuscar.setText("Buscar");
        opcionBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionBuscarActionPerformed(evt);
            }
        });
        menuUsuario.add(opcionBuscar);

        opcionActualizar.setText("Actualizar");
        opcionActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionActualizarActionPerformed(evt);
            }
        });
        menuUsuario.add(opcionActualizar);

        opcionBorrar.setText("Borrar");
        opcionBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionBorrarActionPerformed(evt);
            }
        });
        menuUsuario.add(opcionBorrar);

        opcionRegistrar.setText("Registrar");
        opcionRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionRegistrarActionPerformed(evt);
            }
        });
        menuUsuario.add(opcionRegistrar);

        opcionContraseña.setText("Cambiar Contraseña");
        opcionContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionContraseñaActionPerformed(evt);
            }
        });
        menuUsuario.add(opcionContraseña);

        barraMenu.add(menuUsuario);

        setJMenuBar(barraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcionBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionBuscarActionPerformed
        Buscar buscar = new Buscar();
        buscar.setVisible(true);
    }//GEN-LAST:event_opcionBuscarActionPerformed

    private void opcionActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionActualizarActionPerformed
        Actualizar actualizar = new Actualizar();
        actualizar.setVisible(true);
    }//GEN-LAST:event_opcionActualizarActionPerformed

    private void opcionBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionBorrarActionPerformed
        Borrar borrar = new Borrar();
        borrar.setVisible(true);
    }//GEN-LAST:event_opcionBorrarActionPerformed

    private void opcionRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionRegistrarActionPerformed
        Registrar registrar = new Registrar();
        registrar.setVisible(true);
    }//GEN-LAST:event_opcionRegistrarActionPerformed

    private void opcionContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionContraseñaActionPerformed
        CambiarContraseña cambiar = new CambiarContraseña();
        cambiar.setVisible(true);
        
    }//GEN-LAST:event_opcionContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JLabel etiquetaLiverpool;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JMenuItem opcionActualizar;
    private javax.swing.JMenuItem opcionBorrar;
    private javax.swing.JMenuItem opcionBuscar;
    private javax.swing.JMenuItem opcionContraseña;
    private javax.swing.JMenuItem opcionRegistrar;
    private javax.swing.JPanel panelNombre;
    // End of variables declaration//GEN-END:variables
}
